#!/sbin/sh

. "$env"

print "Disabling all encryption in the fstab..."

found_fstab=false

for fstab in fstab.*; do
	print "Found fstab: $fstab"
	sed -i "s/\b\(forceencrypt\|forcefdeorfbe\|encryptable\)=[^,]*,*//g;s/,$//g" "$fstab"
	found_fstab=true
done

$found_fstab || {
	print "Unable to find the fstab!"
}

print "Disabling encryption trigger in init.rc..."

if [ -f init.rc ]; then
	sed -i '/^on property:vold.decrypt=trigger_encryption$/,/^[^ ]/{//!d};/^service encrypt /,/^[^ ]/{//!d}' init.rc
	sed -i '/^on property:vold.decrypt=trigger_encryption$/d;/^service encrypt /d' init.rc
else
	print "Unable to find init.rc!"
fi

exit 0
